export const DRAWER_TOGGLED = "DRAWER_TOGGLED"

////////////////////
//    EVENTS
///////////////////
export const NEW_EVENT_FORM_UPDATED = "NEW_EVENT_FORM_UPDATED"
export const NEW_EVENT_SAVE_STARTED = "NEW_EVENT_SAVE_STARTED"
export const NEW_EVENT_SAVE_ERROR = "NEW_EVENT_SAVE_ERROR"
export const NEW_EVENT_SAVE_SUCCESS = "NEW_EVENT_SAVE_SUCCESS"
export const NEW_EVENT_CLEARED = "NEW_EVENT_CLEARED"

/*
export const CURRENT_EVENT_RETRIEVED = "CURRENT_EVENT_RETRIEVED"
export const CURRENT_EVENT_FETCH_STARTED = "CURRENT_EVENT_FETCH_STARTED"
export const CURRENT_EVENT_LOADING_ERROR = "CURRENT_EVENT_LOADING_ERROR"
export const CURRENT_EVENT_SAVE_STARTED = "CURRENT_EVENT_SAVED_STARTED"
export const CURRENT_EVENT_SAVE_SUCCESS = "CURRENT_EVENT_SAVED_SUCCESS"
export const CURRENT_EVENT_SAVE_ERROR = "CURRENT_EVENT_SAVE_ERROR"
export const CURRENT_EVENT_CLEARED = "CURRENT_EVENT_CLEARED"

export const EVENTS_RETRIEVED = "EVENTS_RETRIEVED"
export const EVENTS_LOADING_ERROR = "EVENTS_LOADING_ERROR"
export const CURRENT_EVENT_FORM_UPDATED = "CURRENT_EVENT_FORM_UPDATED"
*/
