export const DRAWER_TOGGLED = 'DRAWER_TOGGLED'

export const SET_RESOURCES = 'SET_RESOURCES'
export const GET_CURRENT_RESOURCE = 'GET_CURRENT_RESOURCE'
export const FETCHING_STARTED = 'FETCHING_STARTED'
export const FETCHING_DONE = 'FETCHING_DONE'
